name: Checkstyle

on:
    pull_request:
        branches: [ main, develop ] # PR 대상 브랜치

jobs:
    checkstyle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  java-version: '17' # 프로젝트 JDK 버전
                  distribution: 'temurin'
                  cache: 'gradle'

            - name: Run Gradle Checkstyle
              run: ./gradlew checkstyleMain checkstyleTest

