name: Checkstyle

on:
    pull_request:
        branches: [ main, develop ] # PR 대상 브랜치

jobs:
    checkstyle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  java-version: '21' # 프로젝트 JDK 버전
                  distribution: 'temurin'
                  cache: 'gradle'
                  cache-dependency-path: './backend/back/*.gradle*'


            - name: Run Gradle Checkstyle
              run: ./gradlew checkstyleMain checkstyleTest --build-cache --parallel --no-daemon
              working-directory: backend/back

